Patch 1
Raraph84/Raraph84-Website pull request #1
Opened 2022-02-12 23:12 UTC by Galitan-dev

# Patch 1
Premier patch de ton site.

J'ai regardé vite fait le site et modif les bouts où ça se répétait beaucoup. 
**Fais attention aux fautes d'anglais**

J'espère que dans l'avenir, tu vas faire un Readme et déposer une License, car là c'est pas ouf.

Bonne soirée

*PS: Il est minuit à l'heure ou je fais ce patch, alors s'il y a des typos, soient tolérant...

2022-02-12 23:26 UTC, Raraph84 requested changes
Effectivement y'a des S manquants à certains messages d'erreurs, je fix plus tard
Sinon j'ai mis quelques commentaires là ou y'a des pb

2022-02-12 23:26 UTC, Raraph84 commented on src/account.js
> +            if (this.password.current.value !== this.passwordVerify.current.value)
Pourquoi ça ?

2022-02-12 23:26 UTC, Raraph84 commented on src/account.js
> +                            you_must_accept_CGU: <Info>Vous devez lire et accepter les conditions générales d'utilisation !</Info>,
rip le toLowerCase plus bas

2022-02-12 23:30 UTC, Raraph84 reviewed
Nickel la class Project (sauf quelques trucs j'ai mis des commentaires)

2022-02-12 23:30 UTC, Raraph84 commented on src/account.js
> +            if (this.password.current.value !== this.passwordVerify.current.value) {
J'ai pas compris là non plus

2022-02-12 23:30 UTC, Raraph84 commented on src/home.js
> +        return <a href="{{this.link}}" target="_blank" rel="noreferrer" className="box project">
Sinon tu peux aussi mettre href={this.link}

2022-02-12 23:30 UTC, Raraph84 commented on src/home.js
> +        return <a href="{{this.link}}" target="_blank" rel="noreferrer" className="box project">
Pareil plus bas^^

2022-02-12 23:50 UTC, Raraph84 requested changes
Review depuis mon téléphone, je te laisse modif je vérifierai après sur pc (je fixerait les pb de fautes dans les erreurs sur l'api aussi)

2022-02-12 23:50 UTC, Raraph84 commented on src/account.js
> +                            you_must_accept_CGU: <Info>Vous devez lire et accepter les conditions générales d'utilisation !</Info>,
rip le toLowerCase() plus bas

2022-02-12 23:50 UTC, Raraph84 commented on src/hebergs/hebergs.js
> +        // La suite est une catastrophe, mais flemme de modif
C'était pas la peine ce fichier fallais que je le revoye

2022-02-12 23:50 UTC, Raraph84 commented on src/home.js
> +export class Project extends Component {
Pas besoin de l'export ici

2022-02-12 23:50 UTC, Raraph84 commented on src/index.js
> +const UNAVAILABLE = false; // Je ne sais pas s'il y a moyen de recup depuis l'environnement
Bientôt l'api en public tu t'amuseras

2022-02-12 23:50 UTC, Raraph84 commented on src/index.js
> +                <Switch>
pas besoin d'un switch si y'a qu'une seule route avec *

2022-02-12 23:50 UTC, Raraph84 commented on src/index.js
> +                <Switch>
ni de route dcp

2022-02-12 23:50 UTC, Raraph84 commented on src/index.js
> +                {{
Une seule accolade ça marche aussi

2022-02-13 08:19 UTC, Raraph84 commented
Readme ajouté

2022-02-13 08:55 UTC, Raraph84 commented
Licence aussi ajoutée

2022-02-13 17:13 UTC, Galitan-dev commented on src/index.js
> +                <Switch>
Ah oui pas con x)

2022-02-13 17:14 UTC, Galitan-dev commented on src/home.js
> +export class Project extends Component {
ça coûte rien, mais ok

2022-02-13 17:14 UTC, Galitan-dev commented on src/account.js
> +                            you_must_accept_CGU: <Info>Vous devez lire et accepter les conditions générales d'utilisation !</Info>,
aie

2022-02-13 17:14 UTC, Galitan-dev commented on src/index.js
> +                {{
Je fais du vue en mm temps

2022-02-13 17:15 UTC, Galitan-dev commented
Je fais les modifs

2022-02-13 17:19 UTC, Galitan-dev commented
Ça y est j'ai fait les modifs.

2022-02-13 17:21 UTC, Galitan-dev commented
@Raraph84

2022-02-13 17:22 UTC, Galitan-dev commented on src/hebergs/hebergs.js
> +        // La suite est une catastrophe, mais flemme de modif
Ok

2022-02-13 17:40 UTC, merged