Fixed previous changess
Raraph84/Raraph84-Website pull request #3
Opened 2022-02-13 20:38 UTC by Galitan-dev

# Patch 1 - Fixed
J'ai testé **en local** et rectifié toutes *mes erreurs*.

## Tests:
 - MAINTENANCE Mode: ✅
 - Error messages: ✅
 - Projects: ✅
 - Pretty: ❌

*J'espère que cette fois ci, c'est good.*

2022-02-14 19:12 UTC, Raraph84 requested changes

2022-02-14 19:12 UTC, Raraph84 commented on .gitignore
> +yarn.lock
Met le yarn.lock au dessus du deploy.bat ça me stresse mdr

2022-02-14 19:12 UTC, Raraph84 commented on src/account.js
> +
?

2022-02-14 19:12 UTC, Raraph84 commented on src/account.js
> +
Un retour à la ligne en trop x)

2022-02-14 19:12 UTC, Raraph84 commented on src/home.js
> +
Pareil ici ?

2022-02-14 19:12 UTC, Raraph84 commented on src/home.js
> +class Project extends Component {
C'est pas utilisé je crois

2022-02-14 19:12 UTC, Raraph84 commented on src/home.js
> +class Project extends Component {
tu l'a oublié en haut

2022-02-14 19:12 UTC, Raraph84 commented on src/index.js
> +                        <Route exact path="/freenitro">{() => window.location.assign("https://www.youtube.com/watch?v=dQw4w9WgXcQ")}</Route>
Tu peux l'enlever celui là mdr

2022-02-14 19:12 UTC, Raraph84 commented on src/home.js
> +class Project extends Component {
d'ailleurs au lieu de pid met url

2022-02-14 19:32 UTC, Galitan-dev commented on src/index.js
> +                        <Route exact path="/freenitro">{() => window.location.assign("https://www.youtube.com/watch?v=dQw4w9WgXcQ")}</Route>
C'est pas mon boulot x)

2022-02-14 21:04 UTC, Galitan-dev commented on src/home.js
> +class Project extends Component {
bizarre, les changements ils y sont en local

2022-02-14 21:04 UTC, Galitan-dev commented on src/home.js
> +class Project extends Component {
pid c'est pour project id, et nom je mettrais pas url car ça n'a aucun sens

2022-02-14 21:07 UTC, Galitan-dev commented on .gitignore
> +yarn.lock
inutile

2022-02-14 21:08 UTC, Galitan-dev commented
Ça y est @Raraph84

2022-02-14 21:09 UTC, Galitan-dev commented
Les doubles saut de lignes, c'était mon linter qui bugait car t'avais mis un saut entre 2 imports. Du coup, il le décalait en bas.

2022-02-14 21:10 UTC, Galitan-dev commented
Le reste, c'est vraiment pas le but d'une contribution, mdrrr

2022-02-14 21:10 UTC, Galitan-dev commented
Tu le fais une fois pull à la rigueur

2022-02-14 21:11 UTC, Galitan-dev commented
Allez, à plus 👋

2022-02-15 18:06 UTC, Raraph84 approved these changes

2022-02-17 08:44 UTC, Raraph84 requested changes
Il manque la classe Unavailable dans le other.js :/

2022-02-17 08:46 UTC, Galitan-dev commented
> Il manque la classe Unavailable dans le other.js :/

Ouep j'ai vu

2022-02-17 08:46 UTC, Galitan-dev commented
C'est git qui a buggé lors d'un merge en local

2022-02-17 08:51 UTC, Galitan-dev commented
voilà

2022-02-17 08:57 UTC, Raraph84 approved these changes
Nickel

2022-02-17 09:04 UTC, merged

2022-02-17 09:05 UTC, Raraph84 commented
yes je me suis bien débrouillé avec git cette fois